# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a7e56f9704867ac1aa8c307541715bd6a45cfbd841373263baffefd279d4a646358417408cb3afb744dec5e18ce120e3f8840a5705375caf4f2333432c2e3d81

test:
  secret_key_base: 96f1fb03592e0c77104424007008133d3268dc34020ea69b57592230627d101b5c016bbb0999a4e84234eb684f6ce10ca89184f5e4b6baeaa037cf0260cae3a4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
